package core.classes.pcu;

// default package
// Generated Aug 20, 2014 1:40:33 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * PcuExpireditems generated by hbm2java
 */
public class PcuExpireditems implements java.io.Serializable {

	private PcuExpireditemsId id;
	private Float quantity;
	private Date expiryDate;

	public PcuExpireditems() {
	}

	public PcuExpireditems(PcuExpireditemsId id) {
		this.id = id;
	}

	public PcuExpireditems(PcuExpireditemsId id, Float quantity, Date expiryDate) {
		this.id = id;
		this.quantity = quantity;
		this.expiryDate = expiryDate;
	}

	public PcuExpireditemsId getId() {
		return this.id;
	}

	public void setId(PcuExpireditemsId id) {
		this.id = id;
	}

	public Float getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Float quantity) {
		this.quantity = quantity;
	}

	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

}
