package core.classes.pcu;

// default package
// Generated Aug 26, 2014 5:18:27 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * PcuItemstockday generated by hbm2java
 */
public class PcuItemstockday implements java.io.Serializable {

	private Date date;
	private float stock;

	public PcuItemstockday() {
	}

	public PcuItemstockday(Date date, float stock) {
		this.date = date;
		this.stock = stock;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public float getStock() {
		return this.stock;
	}

	public void setStock(float stock) {
		this.stock = stock;
	}

}
