package core.classes.pcu;

// default package
// Generated Aug 20, 2014 1:40:33 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PcuItems generated by hbm2java
 */
public class PcuItems implements java.io.Serializable {

	private int SNumber;
	private String name;
	private String remark;
	private Date lastStockRecieved;
	private String measurement;
	private Float reorderLevel;
	private Set pcuItembatchrelations = new HashSet(0);

	public PcuItems() {
	}

	public PcuItems(int SNumber, Date lastStockRecieved) {
		this.SNumber = SNumber;
		this.lastStockRecieved = lastStockRecieved;
	}

	public PcuItems(int SNumber, String name, String remark,
			Date lastStockRecieved, String measurement, Float reorderLevel,
			Set pcuItembatchrelations) {
		this.SNumber = SNumber;
		this.name = name;
		this.remark = remark;
		this.lastStockRecieved = lastStockRecieved;
		this.measurement = measurement;
		this.reorderLevel = reorderLevel;
		this.pcuItembatchrelations = pcuItembatchrelations;
	}

	public int getSNumber() {
		return this.SNumber;
	}

	public void setSNumber(int SNumber) {
		this.SNumber = SNumber;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getLastStockRecieved() {
		return this.lastStockRecieved;
	}

	public void setLastStockRecieved(Date lastStockRecieved) {
		this.lastStockRecieved = lastStockRecieved;
	}

	public String getMeasurement() {
		return this.measurement;
	}

	public void setMeasurement(String measurement) {
		this.measurement = measurement;
	}

	public Float getReorderLevel() {
		return this.reorderLevel;
	}

	public void setReorderLevel(Float reorderLevel) {
		this.reorderLevel = reorderLevel;
	}

	public Set getPcuItembatchrelations() {
		return this.pcuItembatchrelations;
	}

	public void setPcuItembatchrelations(Set pcuItembatchrelations) {
		this.pcuItembatchrelations = pcuItembatchrelations;
	}

}
