package core.classes.pcu;

// default package
// Generated Aug 20, 2014 1:40:33 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PcuItembatch generated by hbm2java
 */
public class PcuItembatch implements java.io.Serializable {

	private int batchId;
	private Date recievedDate;
	private Set pcuItembatchrelations = new HashSet(0);

	public PcuItembatch() {
	}

	public PcuItembatch(int batchId) {
		this.batchId = batchId;
	}

	public PcuItembatch(int batchId, Date recievedDate,
			Set pcuItembatchrelations) {
		this.batchId = batchId;
		this.recievedDate = recievedDate;
		this.pcuItembatchrelations = pcuItembatchrelations;
	}

	public int getBatchId() {
		return this.batchId;
	}

	public void setBatchId(int batchId) {
		this.batchId = batchId;
	}

	public Date getRecievedDate() {
		return this.recievedDate;
	}

	public void setRecievedDate(Date recievedDate) {
		this.recievedDate = recievedDate;
	}

	public Set getPcuItembatchrelations() {
		return this.pcuItembatchrelations;
	}

	public void setPcuItembatchrelations(Set pcuItembatchrelations) {
		this.pcuItembatchrelations = pcuItembatchrelations;
	}

}
