package core.classes.pcu;

// default package
// Generated Aug 20, 2014 1:40:33 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * PcuItembatchrelation generated by hbm2java
 */
public class PcuItembatchrelation implements java.io.Serializable {

	private PcuItembatchrelationId id;
	private PcuItems pcuItems;
	private PcuItembatch pcuItembatch;
	private Float quantity;
	private Date expiryDate;

	public PcuItembatchrelation() {
	}

	public PcuItembatchrelation(PcuItembatchrelationId id, PcuItems pcuItems,
			PcuItembatch pcuItembatch) {
		this.id = id;
		this.pcuItems = pcuItems;
		this.pcuItembatch = pcuItembatch;
	}

	public PcuItembatchrelation(PcuItembatchrelationId id, PcuItems pcuItems,
			PcuItembatch pcuItembatch, Float quantity, Date expiryDate) {
		this.id = id;
		this.pcuItems = pcuItems;
		this.pcuItembatch = pcuItembatch;
		this.quantity = quantity;
		this.expiryDate = expiryDate;
	}

	public PcuItembatchrelationId getId() {
		return this.id;
	}

	public void setId(PcuItembatchrelationId id) {
		this.id = id;
	}

	public PcuItems getPcuItems() {
		return this.pcuItems;
	}

	public void setPcuItems(PcuItems pcuItems) {
		this.pcuItems = pcuItems;
	}

	public PcuItembatch getPcuItembatch() {
		return this.pcuItembatch;
	}

	public void setPcuItembatch(PcuItembatch pcuItembatch) {
		this.pcuItembatch = pcuItembatch;
	}

	public Float getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Float quantity) {
		this.quantity = quantity;
	}

	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

}
