package core.classes.pcu;

// default package
// Generated Aug 20, 2014 1:40:33 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * PcuManualdispense generated by hbm2java
 */
public class PcuManualdispense implements java.io.Serializable {

	private Integer id;
	private int admitionId;
	private int SNumber;
	private Date dispensedDate;
	private Integer dispensedBy;
	private Float quanity;

	public PcuManualdispense() {
	}

	public PcuManualdispense(int admitionId, int SNumber) {
		this.admitionId = admitionId;
		this.SNumber = SNumber;
	}

	public PcuManualdispense(int admitionId, int SNumber, Date dispensedDate,
			Integer dispensedBy, Float quanity) {
		this.admitionId = admitionId;
		this.SNumber = SNumber;
		this.dispensedDate = dispensedDate;
		this.dispensedBy = dispensedBy;
		this.quanity = quanity;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getAdmitionId() {
		return this.admitionId;
	}

	public void setAdmitionId(int admitionId) {
		this.admitionId = admitionId;
	}

	public int getSNumber() {
		return this.SNumber;
	}

	public void setSNumber(int SNumber) {
		this.SNumber = SNumber;
	}

	public Date getDispensedDate() {
		return this.dispensedDate;
	}

	public void setDispensedDate(Date dispensedDate) {
		this.dispensedDate = dispensedDate;
	}

	public Integer getDispensedBy() {
		return this.dispensedBy;
	}

	public void setDispensedBy(Integer dispensedBy) {
		this.dispensedBy = dispensedBy;
	}

	public Float getQuanity() {
		return this.quanity;
	}

	public void setQuanity(Float quanity) {
		this.quanity = quanity;
	}

}
