package core.classes.pcu;

import java.util.Date;

import core.classes.api.user.AdminUser;

/**
 * PcuNursenote generated by hbm2java
 */
public class PcuNursenote implements java.io.Serializable {

	private Integer noteId;
	private PcuAdmition pcuPatientId;
	private String noteDetails;
	private AdminUser noteBy;
	private Date noteTime;
	private AdminUser modifiedBy;
	private Date modifiedTime;

	public PcuNursenote() {
	}

	public PcuNursenote(PcuAdmition pcuPatientId, String noteDetails, AdminUser noteBy,
			Date noteTime, AdminUser modifiedBy, Date modifiedTime) {
		this.pcuPatientId = pcuPatientId;
		this.noteDetails = noteDetails;
		this.noteBy = noteBy;
		this.noteTime = noteTime;
		this.modifiedBy = modifiedBy;
		this.modifiedTime = modifiedTime;
	}

	public Integer getNoteId() {
		return this.noteId;
	}

	public void setNoteId(Integer noteId) {
		this.noteId = noteId;
	}

	public PcuAdmition getPcuPatientId() {
		return this.pcuPatientId;
	}

	public void setPcuPatientId(PcuAdmition pcuPatientId) {
		this.pcuPatientId = pcuPatientId;
	}

	public String getNoteDetails() {
		return this.noteDetails;
	}

	public void setNoteDetails(String noteDetails) {
		this.noteDetails = noteDetails;
	}

	public AdminUser getNoteBy() {
		return this.noteBy;
	}

	public void setNoteBy(AdminUser noteBy) {
		this.noteBy = noteBy;
	}

	public Date getNoteTime() {
		return this.noteTime;
	}

	public void setNoteTime(Date noteTime) {
		this.noteTime = noteTime;
	}

	public AdminUser getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(AdminUser modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

}
