package core.classes.pcu;

/**
 * PcuPrescriptionitemsId generated by hbm2java
 */
public class PcuPrescriptionitemsId implements java.io.Serializable {

	private PcuPrescription prescriptionId;
	private PcuItems SNumber;

	public PcuPrescriptionitemsId() {
	}

	public PcuPrescriptionitemsId(PcuPrescription prescriptionId, PcuItems SNumber) {
		this.prescriptionId = prescriptionId;
		this.SNumber = SNumber;
	}

	public PcuPrescription getPrescriptionId() {
		return this.prescriptionId;
	}

	public void setPrescriptionId(PcuPrescription prescriptionId) {
		this.prescriptionId = prescriptionId;
	}

	public PcuItems getSNumber() {
		return this.SNumber;
	}

	public void setSNumber(PcuItems SNumber) {
		this.SNumber = SNumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PcuPrescriptionitemsId))
			return false;
		PcuPrescriptionitemsId castOther = (PcuPrescriptionitemsId) other;

		return (this.getPrescriptionId() == castOther.getPrescriptionId())
				&& (this.getSNumber() == castOther.getSNumber());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPrescriptionId().getPrescriptionId();
		result = 37 * result + this.getSNumber().getSNumber();
		return result;
	}

}
