package core.classes.pcu;

import java.util.Date;

import core.classes.api.user.AdminUser;

/**
 * PcuPrescription generated by hbm2java
 */
public class PcuPrescription implements java.io.Serializable {

	private Integer prescriptionId;
	private PcuAdmition pcuPatientId;
	private int doctorId;
	private String prescriptionDetails;
	private Date prescriptionDate;
	private AdminUser createdBy;
	private Date createdTime;
	private AdminUser modifiedBy;
	private Date modifiedTime;

	public PcuPrescription() {
	}

	public PcuPrescription(PcuAdmition pcuPatientId, int doctorId,
			String prescriptionDetails, Date prescriptionDate, AdminUser createdBy,
			Date createdTime, AdminUser modifiedBy, Date modifiedTime) {
		this.pcuPatientId = pcuPatientId;
		this.doctorId = doctorId;
		this.prescriptionDetails = prescriptionDetails;
		this.prescriptionDate = prescriptionDate;
		this.createdBy = createdBy;
		this.createdTime = createdTime;
		this.modifiedBy = modifiedBy;
		this.modifiedTime = modifiedTime;
	}

	public Integer getPrescriptionId() {
		return this.prescriptionId;
	}

	public void setPrescriptionId(Integer prescriptionId) {
		this.prescriptionId = prescriptionId;
	}

	public PcuAdmition getPcuPatientId() {
		return this.pcuPatientId;
	}

	public void setPcuPatientId(PcuAdmition pcuPatientId) {
		this.pcuPatientId = pcuPatientId;
	}

	public int getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(int doctorId) {
		this.doctorId = doctorId;
	}

	public String getPrescriptionDetails() {
		return this.prescriptionDetails;
	}

	public void setPrescriptionDetails(String prescriptionDetails) {
		this.prescriptionDetails = prescriptionDetails;
	}

	public Date getPrescriptionDate() {
		return this.prescriptionDate;
	}

	public void setPrescriptionDate(Date prescriptionDate) {
		this.prescriptionDate = prescriptionDate;
	}

	public AdminUser getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(AdminUser createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public AdminUser getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(AdminUser modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Date getModifiedTime() {
		return this.modifiedTime;
	}

	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}

}
