package core.classes.pcu;

import java.util.Date;

/**
 * PcuPrescriptionitems generated by hbm2java
 */
public class PcuPrescriptionitems implements java.io.Serializable {

	private PcuPrescriptionitemsId id;
	private Float periodInHours;
	private Float frequencyOfDrug;
	private Float quanity;
	private Date startedDate;
	private Date closedDate;
	private String status;

	public PcuPrescriptionitems() {
	}

	public PcuPrescriptionitems(PcuPrescriptionitemsId id) {
		this.id = id;
	}

	public PcuPrescriptionitems(PcuPrescriptionitemsId id, Float periodInHours,
			Float frequencyOfDrug, Float quanity, Date startedDate,
			Date closedDate, String status) {
		this.id = id;
		this.periodInHours = periodInHours;
		this.frequencyOfDrug = frequencyOfDrug;
		this.quanity = quanity;
		this.startedDate = startedDate;
		this.closedDate = closedDate;
		this.status = status;
	}

	public PcuPrescriptionitemsId getId() {
		return this.id;
	}

	public void setId(PcuPrescriptionitemsId id) {
		this.id = id;
	}

	public Float getPeriodInHours() {
		return this.periodInHours;
	}

	public void setPeriodInHours(Float periodInHours) {
		this.periodInHours = periodInHours;
	}

	public Float getFrequencyOfDrug() {
		return this.frequencyOfDrug;
	}

	public void setFrequencyOfDrug(Float frequencyOfDrug) {
		this.frequencyOfDrug = frequencyOfDrug;
	}

	public Float getQuanity() {
		return this.quanity;
	}

	public void setQuanity(Float quanity) {
		this.quanity = quanity;
	}

	public Date getStartedDate() {
		return this.startedDate;
	}

	public void setStartedDate(Date startedDate) {
		this.startedDate = startedDate;
	}

	public Date getClosedDate() {
		return this.closedDate;
	}

	public void setClosedDate(Date closedDate) {
		this.closedDate = closedDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
