package core.classes.pcu;

/**
 * PcuPatientsymtoms generated by hbm2java
 */
public class PcuPatientsymtoms implements java.io.Serializable {

	private Integer symtomsId;
	private PcuAdmition pcuPatientId;
	private String symtomsDetails;
	private String status;

	public PcuPatientsymtoms() {
	}

	public PcuPatientsymtoms(PcuAdmition pcuPatientId, String symtomsDetails,
			String status) {
		this.pcuPatientId = pcuPatientId;
		this.symtomsDetails = symtomsDetails;
		this.status = status;
	}

	public Integer getSymtomsId() {
		return this.symtomsId;
	}

	public void setSymtomsId(Integer symtomsId) {
		this.symtomsId = symtomsId;
	}

	public PcuAdmition getPcuPatientId() {
		return this.pcuPatientId;
	}

	public void setPcuPatientId(PcuAdmition pcuPatientId) {
		this.pcuPatientId = pcuPatientId;
	}

	public String getSymtomsDetails() {
		return this.symtomsDetails;
	}

	public void setSymtomsDetails(String symtomsDetails) {
		this.symtomsDetails = symtomsDetails;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
