package core.classes.pcu;

// default package
// Generated Aug 20, 2014 1:40:33 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * PcuRequesteditems generated by hbm2java
 */
public class PcuRequesteditems implements java.io.Serializable {

	private Integer id;
	private Integer SNumber;
	private Float quantity;
	private Integer requestedBy;
	private Date requestedDate;
	private String status;

	public PcuRequesteditems() {
	}

	public PcuRequesteditems(Integer SNumber, Float quantity,
			Integer requestedBy, Date requestedDate, String status) {
		this.SNumber = SNumber;
		this.quantity = quantity;
		this.requestedBy = requestedBy;
		this.requestedDate = requestedDate;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getSNumber() {
		return this.SNumber;
	}

	public void setSNumber(Integer SNumber) {
		this.SNumber = SNumber;
	}

	public Float getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Float quantity) {
		this.quantity = quantity;
	}

	public Integer getRequestedBy() {
		return this.requestedBy;
	}

	public void setRequestedBy(Integer requestedBy) {
		this.requestedBy = requestedBy;
	}

	public Date getRequestedDate() {
		return this.requestedDate;
	}

	public void setRequestedDate(Date requestedDate) {
		this.requestedDate = requestedDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
