package core.classes.pcu;

// default package
// Generated Aug 20, 2014 1:40:33 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * PcuViewinventoryId generated by hbm2java
 */
public class PcuViewinventoryId implements java.io.Serializable {

	private int SNumber;
	private String name;
	private String remark;
	private Date lastStockRecieved;
	private Float reorderLevel;
	private Double totQty;

	public PcuViewinventoryId() {
	}

	public PcuViewinventoryId(int SNumber, Date lastStockRecieved) {
		this.SNumber = SNumber;
		this.lastStockRecieved = lastStockRecieved;
	}

	public PcuViewinventoryId(int SNumber, String name, String remark,
			Date lastStockRecieved, Float reorderLevel, Double totQty) {
		this.SNumber = SNumber;
		this.name = name;
		this.remark = remark;
		this.lastStockRecieved = lastStockRecieved;
		this.reorderLevel = reorderLevel;
		this.totQty = totQty;
	}

	public int getSNumber() {
		return this.SNumber;
	}

	public void setSNumber(int SNumber) {
		this.SNumber = SNumber;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getLastStockRecieved() {
		return this.lastStockRecieved;
	}

	public void setLastStockRecieved(Date lastStockRecieved) {
		this.lastStockRecieved = lastStockRecieved;
	}

	public Float getReorderLevel() {
		return this.reorderLevel;
	}

	public void setReorderLevel(Float reorderLevel) {
		this.reorderLevel = reorderLevel;
	}

	public Double getTotQty() {
		return this.totQty;
	}

	public void setTotQty(Double totQty) {
		this.totQty = totQty;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PcuViewinventoryId))
			return false;
		PcuViewinventoryId castOther = (PcuViewinventoryId) other;

		return (this.getSNumber() == castOther.getSNumber())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getRemark() == castOther.getRemark()) || (this
						.getRemark() != null && castOther.getRemark() != null && this
						.getRemark().equals(castOther.getRemark())))
				&& ((this.getLastStockRecieved() == castOther
						.getLastStockRecieved()) || (this
						.getLastStockRecieved() != null
						&& castOther.getLastStockRecieved() != null && this
						.getLastStockRecieved().equals(
								castOther.getLastStockRecieved())))
				&& ((this.getReorderLevel() == castOther.getReorderLevel()) || (this
						.getReorderLevel() != null
						&& castOther.getReorderLevel() != null && this
						.getReorderLevel().equals(castOther.getReorderLevel())))
				&& ((this.getTotQty() == castOther.getTotQty()) || (this
						.getTotQty() != null && castOther.getTotQty() != null && this
						.getTotQty().equals(castOther.getTotQty())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSNumber();
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result
				+ (getRemark() == null ? 0 : this.getRemark().hashCode());
		result = 37
				* result
				+ (getLastStockRecieved() == null ? 0 : this
						.getLastStockRecieved().hashCode());
		result = 37
				* result
				+ (getReorderLevel() == null ? 0 : this.getReorderLevel()
						.hashCode());
		result = 37 * result
				+ (getTotQty() == null ? 0 : this.getTotQty().hashCode());
		return result;
	}

}
