package core.classes.pcu;

// default package
// Generated Aug 20, 2014 1:40:33 PM by Hibernate Tools 4.0.0

/**
 * PcuViewinventory generated by hbm2java
 */
public class PcuViewinventory implements java.io.Serializable {

	private PcuViewinventoryId id;

	public PcuViewinventory() {
	}

	public PcuViewinventory(PcuViewinventoryId id) {
		this.id = id;
	}

	public PcuViewinventoryId getId() {
		return this.id;
	}

	public void setId(PcuViewinventoryId id) {
		this.id = id;
	}

}
