// default package
// Generated Jul 17, 2013 11:31:01 AM by Hibernate Tools 3.4.0.CR1
package core.classes.pharmacy;

import java.util.HashSet;
import java.util.Set;

/**
 * MstDrugCategory generated by hbm2java
 */
public class MstDrugCategory implements java.io.Serializable {

	private Integer dCategoryId;
	private String dCategory;
	private Set<MstDrugsNew> drugs = new HashSet<MstDrugsNew>(0);

	public MstDrugCategory() {
	}

	public MstDrugCategory(String DCategory) {
		this.dCategory = DCategory;
	}

	public Integer getdCategoryId() {
		return dCategoryId;
	}

	public void setdCategoryId(Integer dCategoryId) {
		this.dCategoryId = dCategoryId;
	}

	public String getdCategory() {
		return dCategory;
	}

	public void setdCategory(String dCategory) {
		this.dCategory = dCategory;
	}

	public Set<MstDrugsNew> getDrugs() {
		return drugs;
	}

	public void setDrugs(Set<MstDrugsNew> drugs) {
		this.drugs = drugs;
	}

	

	
	
}
