// default package
// Generated Jul 17, 2013 11:31:01 AM by Hibernate Tools 3.4.0.CR1
package core.classes.pharmacy;
/**
 * MstManufacturer generated by hbm2java
 */
public class MstManufacturer implements java.io.Serializable {

	private Integer mId;
	private String mName;

	public MstManufacturer() {
	}

	public MstManufacturer(String MName) {
		this.mName = MName;
	}

	public Integer getmId() {
		return mId;
	}

	public void setmId(Integer mId) {
		this.mId = mId;
	}

	public String getmName() {
		return mName;
	}

	public void setmName(String mName) {
		this.mName = mName;
	}

	

}
