// default package
// Generated Jul 17, 2013 11:31:01 AM by Hibernate Tools 3.4.0.CR1
package core.classes.pharmacy;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TrnDispenseDrugs generated by hbm2java
 */
public class TrnDispenseDrugs implements java.io.Serializable {

	private int dispenseId;
	private int userId;
	private Date dispensedDate;
	private Integer quantity;
	private MstDrugsNew drugs;

	
	public TrnDispenseDrugs() {
	}


	public int getDispenseId() {
		return dispenseId;
	}


	public void setDispenseId(int dispenseId) {
		this.dispenseId = dispenseId;
	}


	public int getUserId() {
		return userId;
	}


	public void setUserId(int userId) {
		this.userId = userId;
	}


	public Date getDispensedDate() {
		return dispensedDate;
	}


	public void setDispensedDate(Date dispensedDate) {
		this.dispensedDate = dispensedDate;
	}


	public Integer getQuantity() {
		return quantity;
	}


	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}


	public MstDrugsNew getDrugs() {
		return drugs;
	}


	public void setDrugs(MstDrugsNew drugs) {
		this.drugs = drugs;
	}
	
	


}
