// default package
// Generated Jul 17, 2013 11:31:01 AM by Hibernate Tools 3.4.0.CR1
package core.classes.pharmacy;
/**
 * TrnDrugsSuppliedId generated by hbm2java
 */
public class TrnDrugsSuppliedId implements java.io.Serializable {

	private MstDrugsNew drugs;
	private String dBatchNo;

	public TrnDrugsSuppliedId() {
	}

	public TrnDrugsSuppliedId(MstDrugsNew drugs, String DBatchNo) {
		this.drugs = drugs;
		this.dBatchNo = DBatchNo;
	}



	

	public MstDrugsNew getDrugs() {
		return drugs;
	}

	public void setDrugs(MstDrugsNew drugs) {
		this.drugs = drugs;
	}

	public String getdBatchNo() {
		return dBatchNo;
	}

	public void setdBatchNo(String dBatchNo) {
		this.dBatchNo = dBatchNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TrnDrugsSuppliedId))
			return false;
		TrnDrugsSuppliedId castOther = (TrnDrugsSuppliedId) other;

		return (this.getDrugs() == castOther.getDrugs())
				&& ((this.getdBatchNo() == castOther.getdBatchNo()) || (this
						.getdBatchNo() != null
						&& castOther.getdBatchNo() != null && this
						.getdBatchNo().equals(castOther.getdBatchNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + Integer.parseInt(this.getDrugs().toString());
		result = 37 * result
				+ (getdBatchNo() == null ? 0 : this.getdBatchNo().hashCode());
		return result;
	}

}
