// default package
// Generated Jul 17, 2013 11:31:01 AM by Hibernate Tools 3.4.0.CR1
package core.classes.pharmacy;


import java.util.Date;

/**
 * TrnRequestDrugs generated by hbm2java
 */
public class TrnRequestDrugs implements java.io.Serializable {

	private int requestId;
	private MstDrugsNew drugs;
	private String department;
	private Date requestedDate;
	private Date processedDate;
	private Integer quantity;
	private Boolean processed;

	public TrnRequestDrugs() {
	}

	
	public int getRequestId() {
		return requestId;
	}


	public void setRequestId(int requestId) {
		this.requestId = requestId;
	}


	public MstDrugsNew getDrugs() {
		return drugs;
	}


	public void setDrugs(MstDrugsNew drugs) {
		this.drugs = drugs;
	}


	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public Date getRequestedDate() {
		return this.requestedDate;
	}

	public void setRequestedDate(Date requestedDate) {
		this.requestedDate = requestedDate;
	}

	public Date getProcessedDate() {
		return this.processedDate;
	}

	public void setProcessedDate(Date processedDate) {
		this.processedDate = processedDate;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Boolean getProcessed() {
		return this.processed;
	}

	public void setProcessed(Boolean processed) {
		this.processed = processed;
	}

}
