package core.classes.api.user;

import java.util.HashSet;
import java.util.Set;

/**
 * AdminUserroles generated by hbm2java
 */
public class AdminUserroles implements java.io.Serializable {

	private Integer roleId;
	private String roleName;
	private boolean isActive;
	private Set adminUsers = new HashSet(0);
	private Set adminPermissions = new HashSet(0);

	public AdminUserroles() {
	}

	public AdminUserroles(String roleName, boolean isActive) {
		this.roleName = roleName;
		this.isActive = isActive;
	}

	public AdminUserroles(String roleName, boolean isActive, Set adminUsers,
			Set adminPermissions) {
		this.roleName = roleName;
		this.isActive = isActive;
		this.adminUsers = adminUsers;
		this.adminPermissions = adminPermissions;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	public Set getAdminUsers() {
		return this.adminUsers;
	}

	public void setAdminUsers(Set adminUsers) {
		this.adminUsers = adminUsers;
	}

	public Set getAdminPermissions() {
		return this.adminPermissions;
	}

	public void setAdminPermissions(Set adminPermissions) {
		this.adminPermissions = adminPermissions;
	}

}
