package core.classes.api.user;

import java.util.HashSet;
import java.util.Set;

/**
 * AdminPermission generated by hbm2java
 */
public class AdminPermission implements java.io.Serializable {

	private Integer permissionId;
	private String permissionDiscription;
	private boolean isActive;
	private Set adminUserroleses = new HashSet(0);

	public AdminPermission() {
	}

	public AdminPermission(String permissionDiscription, boolean isActive) {
		this.permissionDiscription = permissionDiscription;
		this.isActive = isActive;
	}

	public AdminPermission(String permissionDiscription, boolean isActive,
			Set adminUserroleses) {
		this.permissionDiscription = permissionDiscription;
		this.isActive = isActive;
		this.adminUserroleses = adminUserroleses;
	}

	public Integer getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(Integer permissionId) {
		this.permissionId = permissionId;
	}

	public String getPermissionDiscription() {
		return this.permissionDiscription;
	}

	public void setPermissionDiscription(String permissionDiscription) {
		this.permissionDiscription = permissionDiscription;
	}

	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	public Set getAdminUserroleses() {
		return this.adminUserroleses;
	}

	public void setAdminUserroleses(Set adminUserroleses) {
		this.adminUserroleses = adminUserroleses;
	}

}
