package core.classes.hr;

// default package
// Generated Aug 26, 2014 4:29:26 PM by Hibernate Tools 4.0.0

/**
 * HrAssignschedule generated by hbm2java
 */
public class HrAssignschedule implements java.io.Serializable {

	private HrAssignscheduleId id;
	private HrEmployee hrEmployee;
	private HrShifttimes hrShifttimes;
	private String description;

	public HrAssignschedule() {
	}

	public HrAssignschedule(HrAssignscheduleId id, HrEmployee hrEmployee,
			HrShifttimes hrShifttimes) {
		this.id = id;
		this.hrEmployee = hrEmployee;
		this.hrShifttimes = hrShifttimes;
	}

	public HrAssignschedule(HrAssignscheduleId id, HrEmployee hrEmployee,
			HrShifttimes hrShifttimes, String description) {
		this.id = id;
		this.hrEmployee = hrEmployee;
		this.hrShifttimes = hrShifttimes;
		this.description = description;
	}

	public HrAssignscheduleId getId() {
		return this.id;
	}

	public void setId(HrAssignscheduleId id) {
		this.id = id;
	}

	public HrEmployee getHrEmployee() {
		return this.hrEmployee;
	}

	public void setHrEmployee(HrEmployee hrEmployee) {
		this.hrEmployee = hrEmployee;
	}

	public HrShifttimes getHrShifttimes() {
		return this.hrShifttimes;
	}

	public void setHrShifttimes(HrShifttimes hrShifttimes) {
		this.hrShifttimes = hrShifttimes;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
