package core.classes.hr;

// default package
// Generated Aug 25, 2014 2:45:14 PM by Hibernate Tools 4.0.0

/**
 * HrContactId generated by hbm2java
 */
public class HrContactId implements java.io.Serializable {

	private int contactTypeId;
	private int empId;

	public HrContactId() {
	}

	public HrContactId(int contactTypeId, int empId) {
		this.contactTypeId = contactTypeId;
		this.empId = empId;
	}

	public int getContactTypeId() {
		return this.contactTypeId;
	}

	public void setContactTypeId(int contactTypeId) {
		this.contactTypeId = contactTypeId;
	}

	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HrContactId))
			return false;
		HrContactId castOther = (HrContactId) other;

		return (this.getContactTypeId() == castOther.getContactTypeId())
				&& (this.getEmpId() == castOther.getEmpId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getContactTypeId();
		result = 37 * result + this.getEmpId();
		return result;
	}

}
