package core.classes.hr;

// default package
// Generated Aug 25, 2014 2:45:14 PM by Hibernate Tools 4.0.0

/**
 * HrContact generated by hbm2java
 */
public class HrContact implements java.io.Serializable {

	private HrContactId id;
	private HrEmployee hrEmployee;
	private HrContacttype hrContacttype;
	private String contact;

	public HrContact() {
	}

	public HrContact(HrContactId id, HrEmployee hrEmployee,
			HrContacttype hrContacttype, String contact) {
		this.id = id;
		this.hrEmployee = hrEmployee;
		this.hrContacttype = hrContacttype;
		this.contact = contact;
	}

	public HrContactId getId() {
		return this.id;
	}

	public void setId(HrContactId id) {
		this.id = id;
	}

	public HrEmployee getHrEmployee() {
		return this.hrEmployee;
	}

	public void setHrEmployee(HrEmployee hrEmployee) {
		this.hrEmployee = hrEmployee;
	}

	public HrContacttype getHrContacttype() {
		return this.hrContacttype;
	}

	public void setHrContacttype(HrContacttype hrContacttype) {
		this.hrContacttype = hrContacttype;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

}
