package core.classes.hr;

// default package
// Generated Aug 25, 2014 2:45:14 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * HrContacttype generated by hbm2java
 */
public class HrContacttype implements java.io.Serializable {

	private Integer contactTypeId;
	private String contactType;
	private Set<HrContact> hrContacts = new HashSet<HrContact>();

	public HrContacttype() {
	}

	public HrContacttype(String contactType) {
		this.contactType = contactType;
	}

	public HrContacttype(String contactType, Set<HrContact> hrContacts) {
		this.contactType = contactType;
		this.hrContacts = hrContacts;
	}

	public Integer getContactTypeId() {
		return this.contactTypeId;
	}

	public void setContactTypeId(Integer contactTypeId) {
		this.contactTypeId = contactTypeId;
	}

	public String getContactType() {
		return this.contactType;
	}

	public void setContactType(String contactType) {
		this.contactType = contactType;
	}

	public Set<HrContact> getHrContacts() {
		return this.hrContacts;
	}

	public void setHrContacts(Set hrContacts) {
		this.hrContacts = hrContacts;
	}

}
