package core.classes.hr;

// default package
// Generated Sep 18, 2014 6:25:19 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * HrDesignation generated by hbm2java
 */
public class HrDesignation implements java.io.Serializable {

	private Integer designationId;
	private HrDesignationgroup hrDesignationgroup;
	private String designationName;
	private Set hrWorkins = new HashSet(0);

	public HrDesignation() {
	}

	public HrDesignation(String designationName) {
		this.designationName = designationName;
	}

	public HrDesignation(HrDesignationgroup hrDesignationgroup,
			String designationName, Set hrWorkins) {
		this.hrDesignationgroup = hrDesignationgroup;
		this.designationName = designationName;
		this.hrWorkins = hrWorkins;
	}

	public Integer getDesignationId() {
		return this.designationId;
	}

	public void setDesignationId(Integer designationId) {
		this.designationId = designationId;
	}

	public HrDesignationgroup getHrDesignationgroup() {
		return this.hrDesignationgroup;
	}

	public void setHrDesignationgroup(HrDesignationgroup hrDesignationgroup) {
		this.hrDesignationgroup = hrDesignationgroup;
	}

	public String getDesignationName() {
		return this.designationName;
	}

	public void setDesignationName(String designationName) {
		this.designationName = designationName;
	}

	public Set getHrWorkins() {
		return this.hrWorkins;
	}

	public void setHrWorkins(Set hrWorkins) {
		this.hrWorkins = hrWorkins;
	}

}
