package core.classes.hr;

// default package
// Generated Sep 18, 2014 6:25:19 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * HrDesignationgroup generated by hbm2java
 */
public class HrDesignationgroup implements java.io.Serializable {

	private Integer groupId;
	private String groupName;
	private Set hrDesignations = new HashSet(0);

	public HrDesignationgroup() {
	}

	public HrDesignationgroup(String groupName) {
		this.groupName = groupName;
	}

	public HrDesignationgroup(String groupName, Set hrDesignations) {
		this.groupName = groupName;
		this.hrDesignations = hrDesignations;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public Set getHrDesignations() {
		return this.hrDesignations;
	}

	public void setHrDesignations(Set hrDesignations) {
		this.hrDesignations = hrDesignations;
	}

}
