package core.classes.hr;

// default package
// Generated Sep 18, 2014 6:25:19 PM by Hibernate Tools 4.0.0

/**
 * HrEmployeeView generated by hbm2java
 */
public class HrEmployeeView implements java.io.Serializable {

	private HrEmployeeViewId id;

	public HrEmployeeView() {
	}

	public HrEmployeeView(HrEmployeeViewId id) {
		this.id = id;
	}

	public HrEmployeeViewId getId() {
		return this.id;
	}

	public void setId(HrEmployeeViewId id) {
		this.id = id;
	}

}
