package core.classes.hr;

// default package
// Generated Sep 18, 2014 6:25:19 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HrEmployee generated by hbm2java
 */
public class HrEmployee implements java.io.Serializable {

	private Integer empId;
	private String title;
	private String firstName;
	private String lastName;
	private Date birthday;
	private String gender;
	private String civilStatus;
	private String empImage;
	private boolean isActive;
	private Set hrHasleaveses = new HashSet(0);
	private Set hrDepartments = new HashSet(0);
	private Set adminUsers = new HashSet(0);
	private Set hrIdentities = new HashSet(0);
	private Set hrWorkins = new HashSet(0);
	private Set hrContacts = new HashSet(0);
	private Set hrTakeleaveses = new HashSet(0);
	private Set hrAttendances = new HashSet(0);
	private Set hrAssignschedules = new HashSet(0);

	public HrEmployee() {
	}

	public HrEmployee(String title, String firstName, String lastName,
			Date birthday, String gender, String civilStatus, boolean isActive) {
		this.title = title;
		this.firstName = firstName;
		this.lastName = lastName;
		this.birthday = birthday;
		this.gender = gender;
		this.civilStatus = civilStatus;
		this.isActive = isActive;
	}

	public HrEmployee(String title, String firstName, String lastName,
			Date birthday, String gender, String civilStatus, String empImage,
			boolean isActive, Set hrHasleaveses, Set hrDepartments,
			Set adminUsers, Set hrIdentities, Set hrWorkins, Set hrContacts,
			Set hrTakeleaveses, Set hrAttendances, Set hrAssignschedules) {
		this.title = title;
		this.firstName = firstName;
		this.lastName = lastName;
		this.birthday = birthday;
		this.gender = gender;
		this.civilStatus = civilStatus;
		this.empImage = empImage;
		this.isActive = isActive;
		this.hrHasleaveses = hrHasleaveses;
		this.hrDepartments = hrDepartments;
		this.adminUsers = adminUsers;
		this.hrIdentities = hrIdentities;
		this.hrWorkins = hrWorkins;
		this.hrContacts = hrContacts;
		this.hrTakeleaveses = hrTakeleaveses;
		this.hrAttendances = hrAttendances;
		this.hrAssignschedules = hrAssignschedules;
	}

	public Integer getEmpId() {
		return this.empId;
	}

	public void setEmpId(Integer empId) {
		this.empId = empId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getCivilStatus() {
		return this.civilStatus;
	}

	public void setCivilStatus(String civilStatus) {
		this.civilStatus = civilStatus;
	}

	public String getEmpImage() {
		return this.empImage;
	}

	public void setEmpImage(String empImage) {
		this.empImage = empImage;
	}

	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	public Set getHrHasleaveses() {
		return this.hrHasleaveses;
	}

	public void setHrHasleaveses(Set hrHasleaveses) {
		this.hrHasleaveses = hrHasleaveses;
	}

	public Set getHrDepartments() {
		return this.hrDepartments;
	}

	public void setHrDepartments(Set hrDepartments) {
		this.hrDepartments = hrDepartments;
	}

	public Set getAdminUsers() {
		return this.adminUsers;
	}

	public void setAdminUsers(Set adminUsers) {
		this.adminUsers = adminUsers;
	}

	public Set getHrIdentities() {
		return this.hrIdentities;
	}

	public void setHrIdentities(Set hrIdentities) {
		this.hrIdentities = hrIdentities;
	}

	public Set getHrWorkins() {
		return this.hrWorkins;
	}

	public void setHrWorkins(Set hrWorkins) {
		this.hrWorkins = hrWorkins;
	}

	public Set getHrContacts() {
		return this.hrContacts;
	}

	public void setHrContacts(Set hrContacts) {
		this.hrContacts = hrContacts;
	}

	public Set getHrTakeleaveses() {
		return this.hrTakeleaveses;
	}

	public void setHrTakeleaveses(Set hrTakeleaveses) {
		this.hrTakeleaveses = hrTakeleaveses;
	}

	public Set getHrAttendances() {
		return this.hrAttendances;
	}

	public void setHrAttendances(Set hrAttendances) {
		this.hrAttendances = hrAttendances;
	}

	public Set getHrAssignschedules() {
		return this.hrAssignschedules;
	}

	public void setHrAssignschedules(Set hrAssignschedules) {
		this.hrAssignschedules = hrAssignschedules;
	}

}
