package core.classes.hr;

// default package
// Generated Aug 25, 2014 2:45:14 PM by Hibernate Tools 4.0.0

/**
 * HrHasleaves generated by hbm2java
 */
public class HrHasleaves implements java.io.Serializable {

	private HrHasleavesId id;
	private HrEmployee hrEmployee;
	private HrLeavetype hrLeavetype;
	private int total;
	private int remain;

	public HrHasleaves() {
	}

	public HrHasleaves(HrHasleavesId id, HrEmployee hrEmployee,
			HrLeavetype hrLeavetype, int total, int remain) {
		this.id = id;
		this.hrEmployee = hrEmployee;
		this.hrLeavetype = hrLeavetype;
		this.total = total;
		this.remain = remain;
	}

	public HrHasleavesId getId() {
		return this.id;
	}

	public void setId(HrHasleavesId id) {
		this.id = id;
	}

	public HrEmployee getHrEmployee() {
		return this.hrEmployee;
	}

	public void setHrEmployee(HrEmployee hrEmployee) {
		this.hrEmployee = hrEmployee;
	}

	public HrLeavetype getHrLeavetype() {
		return this.hrLeavetype;
	}

	public void setHrLeavetype(HrLeavetype hrLeavetype) {
		this.hrLeavetype = hrLeavetype;
	}

	public int getTotal() {
		return this.total;
	}

	public void setTotal(int total) {
		this.total = total;
	}

	public int getRemain() {
		return this.remain;
	}

	public void setRemain(int remain) {
		this.remain = remain;
	}

}
