package core.classes.hr;

// default package
// Generated Aug 25, 2014 2:45:14 PM by Hibernate Tools 4.0.0

/**
 * HrIdentity generated by hbm2java
 */
public class HrIdentity implements java.io.Serializable {

	private HrIdentityId id;
	private HrIdentitytype hrIdentitytype;
	private HrEmployee hrEmployee;
	private String identity;

	public HrIdentity() {
	}

	public HrIdentity(HrIdentityId id, HrIdentitytype hrIdentitytype,
			HrEmployee hrEmployee, String identity) {
		this.id = id;
		this.hrIdentitytype = hrIdentitytype;
		this.hrEmployee = hrEmployee;
		this.identity = identity;
	}

	public HrIdentityId getId() {
		return this.id;
	}

	public void setId(HrIdentityId id) {
		this.id = id;
	}

	public HrIdentitytype getHrIdentitytype() {
		return this.hrIdentitytype;
	}

	public void setHrIdentitytype(HrIdentitytype hrIdentitytype) {
		this.hrIdentitytype = hrIdentitytype;
	}

	public HrEmployee getHrEmployee() {
		return this.hrEmployee;
	}

	public void setHrEmployee(HrEmployee hrEmployee) {
		this.hrEmployee = hrEmployee;
	}

	public String getIdentity() {
		return this.identity;
	}

	public void setIdentity(String identity) {
		this.identity = identity;
	}

}
