package core.classes.hr;

// default package
// Generated Aug 25, 2014 2:45:14 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * HrLeavetype generated by hbm2java
 */
public class HrLeavetype implements java.io.Serializable {

	private Integer leaveTypeId;
	private String leaveType;
	private int noOfDays;
	private Set hrTakeleaveses = new HashSet(0);
	private Set hrHasleaveses = new HashSet(0);

	public HrLeavetype() {
	}

	public HrLeavetype(String leaveType, int noOfDays) {
		this.leaveType = leaveType;
		this.noOfDays = noOfDays;
	}

	public HrLeavetype(String leaveType, int noOfDays, Set hrTakeleaveses,
			Set hrHasleaveses) {
		this.leaveType = leaveType;
		this.noOfDays = noOfDays;
		this.hrTakeleaveses = hrTakeleaveses;
		this.hrHasleaveses = hrHasleaveses;
	}

	public Integer getLeaveTypeId() {
		return this.leaveTypeId;
	}

	public void setLeaveTypeId(Integer leaveTypeId) {
		this.leaveTypeId = leaveTypeId;
	}

	public String getLeaveType() {
		return this.leaveType;
	}

	public void setLeaveType(String leaveType) {
		this.leaveType = leaveType;
	}

	public int getNoOfDays() {
		return this.noOfDays;
	}

	public void setNoOfDays(int noOfDays) {
		this.noOfDays = noOfDays;
	}

	public Set getHrTakeleaveses() {
		return this.hrTakeleaveses;
	}

	public void setHrTakeleaveses(Set hrTakeleaveses) {
		this.hrTakeleaveses = hrTakeleaveses;
	}

	public Set getHrHasleaveses() {
		return this.hrHasleaveses;
	}

	public void setHrHasleaveses(Set hrHasleaveses) {
		this.hrHasleaveses = hrHasleaveses;
	}

}
