package core.classes.hr;

// default package
// Generated Aug 26, 2014 4:29:26 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HrShifttimes generated by hbm2java
 */
public class HrShifttimes implements java.io.Serializable {

	private Integer shiftId;
	private HrDepartment hrDepartment;
	private Date fromDatetime;
	private Date toDatetime;
	private Set hrAssignschedules = new HashSet(0);

	public HrShifttimes() {
	}

	public HrShifttimes(HrDepartment hrDepartment, Date fromDatetime,
			Date toDatetime) {
		this.hrDepartment = hrDepartment;
		this.fromDatetime = fromDatetime;
		this.toDatetime = toDatetime;
	}

	public HrShifttimes(HrDepartment hrDepartment, Date fromDatetime,
			Date toDatetime, Set hrAssignschedules) {
		this.hrDepartment = hrDepartment;
		this.fromDatetime = fromDatetime;
		this.toDatetime = toDatetime;
		this.hrAssignschedules = hrAssignschedules;
	}

	public Integer getShiftId() {
		return this.shiftId;
	}

	public void setShiftId(Integer shiftId) {
		this.shiftId = shiftId;
	}

	public HrDepartment getHrDepartment() {
		return this.hrDepartment;
	}

	public void setHrDepartment(HrDepartment hrDepartment) {
		this.hrDepartment = hrDepartment;
	}

	public Date getFromDatetime() {
		return this.fromDatetime;
	}

	public void setFromDatetime(Date fromDatetime) {
		this.fromDatetime = fromDatetime;
	}

	public Date getToDatetime() {
		return this.toDatetime;
	}

	public void setToDatetime(Date toDatetime) {
		this.toDatetime = toDatetime;
	}

	public Set getHrAssignschedules() {
		return this.hrAssignschedules;
	}

	public void setHrAssignschedules(Set hrAssignschedules) {
		this.hrAssignschedules = hrAssignschedules;
	}

}
