package core.classes.hr;

// default package
// Generated Aug 25, 2014 2:45:14 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * HrTakeleaves generated by hbm2java
 */
public class HrTakeleaves implements java.io.Serializable {

	private Integer id;
	private HrEmployee hrEmployee;
	private HrLeavetype hrLeavetype;
	private String startDatetime;
	private String endDatetime;
	private String reason;
	private String approveStatus;
	private HrEmployee approver;

	public HrEmployee getApprover() {
		return approver;
	}

	public void setApprover(HrEmployee approver) {
		this.approver = approver;
	}

	public HrTakeleaves() {
	}

	public HrTakeleaves(Integer id, HrEmployee hrEmployee,
			HrLeavetype hrLeavetype, String startDatetime, String endDatetime,
			String reason, String approveStatus) {
		this.id = id;
		this.hrEmployee = hrEmployee;
		this.hrLeavetype = hrLeavetype;
		this.startDatetime = startDatetime;
		this.endDatetime = endDatetime;
		this.reason = reason;
		this.approveStatus = approveStatus;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public HrEmployee getHrEmployee() {
		return this.hrEmployee;
	}

	public void setHrEmployee(HrEmployee hrEmployee) {
		this.hrEmployee = hrEmployee;
	}

	public HrLeavetype getHrLeavetype() {
		return this.hrLeavetype;
	}

	public void setHrLeavetype(HrLeavetype hrLeavetype) {
		this.hrLeavetype = hrLeavetype;
	}

	public String getStartDatetime() {
		return this.startDatetime;
	}

	public void setStartDatetime(String startDatetime) {
		this.startDatetime = startDatetime;
	}

	public String getEndDatetime() {
		return this.endDatetime;
	}

	public void setEndDatetime(String endDatetime) {
		this.endDatetime = endDatetime;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public String getApproveStatus() {
		return this.approveStatus;
	}

	public void setApproveStatus(String approveStatus) {
		this.approveStatus = approveStatus;
	}

}
