package core.classes.hr;

// default package
// Generated Aug 25, 2014 2:45:14 PM by Hibernate Tools 4.0.0

/**
 * HrWorkinId generated by hbm2java
 */
public class HrWorkinId implements java.io.Serializable {

	private int empId;
	private int deptId;
	private int designationId;

	public HrWorkinId() {
	}

	public HrWorkinId(int empId, int deptId, int designationId) {
		this.empId = empId;
		this.deptId = deptId;
		this.designationId = designationId;
	}

	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	public int getDeptId() {
		return this.deptId;
	}

	public void setDeptId(int deptId) {
		this.deptId = deptId;
	}

	public int getDesignationId() {
		return this.designationId;
	}

	public void setDesignationId(int designationId) {
		this.designationId = designationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HrWorkinId))
			return false;
		HrWorkinId castOther = (HrWorkinId) other;

		return (this.getEmpId() == castOther.getEmpId())
				&& (this.getDeptId() == castOther.getDeptId())
				&& (this.getDesignationId() == castOther.getDesignationId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEmpId();
		result = 37 * result + this.getDeptId();
		result = 37 * result + this.getDesignationId();
		return result;
	}

}
